package main.java.Token;

public enum InstructionType {
    OPERATOR,
    OPERATOR_ADDITIVE,
    OPERATOR_MULTIPLICATIVE,
    OPERATOR_LOGICAL,
    OPERATOR_RELATIONAL,
    OPERATOR_ASSIGNMENT,
    CONDITIONAL,
    OTHER,
    DATA_TYPE,
    LITERAL;
}
