package main.java.Token;

public enum InstructionType {
    CONDITIONAL,
    DATA_TYPE,
    LITERAL,
    LOOP,
    OPERATOR,
    OPERATOR_ADDITIVE,
    OPERATOR_ASSIGNMENT,
    OPERATOR_LOGICAL,
    OPERATOR_MULTIPLICATIVE,
    OPERATOR_RELATIONAL,
    OTHER;
}
